"""Elementary cellular automata (ECA): simulation and symmetry.

This module is deliberately self-contained and dependency-light (NumPy only).
It provides:

* :class:`ECASimulator` — vectorised evolution of a single ECA rule under
  periodic boundary conditions.
* Symmetry helpers (:func:`reflect`, :func:`complement`,
  :func:`equivalence_class`, :func:`independent_rules`) that compute the
  88 ECA equivalence classes *programmatically*.

Why the symmetry matters here: the 256 ECA rules collapse to 88 classes under
left-right reflection and 0<->1 complementation. Rules within a class are the
"same" automaton up to relabelling space or states, so they produce behaviour
that is identical up to those symmetries. Training and evaluation use one
canonical representative per class to avoid double-counting behaviour. The
empirical Li-Packard / Wolfram *behavioural* classes are a different, coarser
notion supplied externally (see BUILD_BRIEF.md §3.6) — they are intentionally
**not** defined in this module.
"""

from __future__ import annotations

import numpy as np

__all__ = [
    "ECASimulator",
    "reflect",
    "complement",
    "equivalence_class",
    "independent_rules",
]


# ---------------------------------------------------------------------------
# Symmetry of the rule space
# ---------------------------------------------------------------------------
#
# A rule's 8-bit table maps each 3-cell neighbourhood ``(left, centre, right)``
# to an output bit. We index a neighbourhood by ``4*left + 2*centre + right``
# (an integer in 0..7), and bit ``i`` of the Wolfram rule number is the output
# for neighbourhood ``i``. The two generating symmetries permute / invert these
# entries; everything below is derived from that single convention.


def _neighbourhood_bits(index: int) -> tuple[int, int, int]:
    """Decompose a neighbourhood index 0..7 into ``(left, centre, right)``."""
    return (index >> 2) & 1, (index >> 1) & 1, index & 1


def reflect(rule: int) -> int:
    """Return the left-right mirror image of ``rule``.

    Reflection swaps the left and right neighbours, so the reflected rule's
    output for neighbourhood ``(l, c, r)`` is the original rule's output for
    ``(r, c, l)``.
    """
    _validate_rule(rule)
    mirrored = 0
    for index in range(8):
        left, centre, right = _neighbourhood_bits(index)
        source = (right << 2) | (centre << 1) | left
        mirrored |= ((rule >> source) & 1) << index
    return mirrored


def complement(rule: int) -> int:
    """Return the 0<->1 (black/white) complement of ``rule``.

    Complementation inverts every cell value, on both input and output: the
    complemented rule's output for neighbourhood ``n`` is the *inverse* of the
    original rule's output for the bit-flipped neighbourhood ``n XOR 0b111``.
    """
    _validate_rule(rule)
    complemented = 0
    for index in range(8):
        source = index ^ 0b111
        complemented |= (1 - ((rule >> source) & 1)) << index
    return complemented


def equivalence_class(rule: int) -> frozenset[int]:
    """Return the set of rules equivalent to ``rule``.

    The symmetry group is generated by :func:`reflect` and :func:`complement`,
    which commute and are each involutions, giving a group of order 4. The
    class is therefore ``{rule, reflect, complement, reflect∘complement}`` —
    of size 1, 2 or 4 once duplicates collapse.
    """
    _validate_rule(rule)
    c = complement(rule)
    return frozenset({rule, reflect(rule), c, reflect(c)})


def independent_rules() -> list[int]:
    """Return one canonical representative (the minimum) of every ECA class.

    There are exactly 88 such classes; this is asserted in the test suite and
    used everywhere a non-redundant set of rules is needed.
    """
    representatives = {min(equivalence_class(rule)) for rule in range(256)}
    return sorted(representatives)


def _validate_rule(rule: int) -> None:
    if not (0 <= rule <= 255):
        raise ValueError(f"ECA rule must be in 0..255, got {rule}")


# ---------------------------------------------------------------------------
# Simulation
# ---------------------------------------------------------------------------


class ECASimulator:
    """Simulate a single elementary cellular automaton.

    Convention (BUILD_BRIEF.md §3.1): row 0 of an output diagram is the initial
    condition at the top; time increases downward; boundaries are periodic.

    Parameters
    ----------
    rule:
        Wolfram rule number in ``0..255``.
    """

    def __init__(self, rule: int) -> None:
        _validate_rule(rule)
        self.rule = rule
        # Lookup table: ``table[i]`` is the output bit for neighbourhood ``i``
        # (i = 4*left + 2*centre + right), i.e. bit ``i`` of the rule number.
        self.table: np.ndarray = np.array([(rule >> i) & 1 for i in range(8)], dtype=np.uint8)

    def step(self, row: np.ndarray) -> np.ndarray:
        """Advance a single row one time step under periodic boundaries.

        Vectorised across the whole row — no per-cell Python loop.
        """
        left = np.roll(row, 1)  # neighbour at index i-1
        right = np.roll(row, -1)  # neighbour at index i+1
        index = (left << 2) | (row << 1) | right
        return self.table[index]

    def evolve(self, initial_row: np.ndarray, n_steps: int) -> np.ndarray:
        """Evolve ``initial_row`` and return an ``(n_steps, width)`` diagram.

        Row 0 is the initial condition; rows 1..``n_steps``-1 are successive
        applications of the rule. Output dtype is ``uint8`` with values in
        ``{0, 1}``.
        """
        if n_steps < 1:
            raise ValueError(f"n_steps must be >= 1, got {n_steps}")
        row = np.asarray(initial_row, dtype=np.uint8).ravel()
        width = row.shape[0]
        diagram = np.empty((n_steps, width), dtype=np.uint8)
        diagram[0] = row
        for t in range(1, n_steps):
            row = self.step(row)
            diagram[t] = row
        return diagram

    def random_diagram(self, width: int, n_steps: int, rng: np.random.Generator) -> np.ndarray:
        """Evolve from a random binary initial row.

        ``rng`` is an explicit :class:`numpy.random.Generator` so diagrams are
        reproducible given a seeded generator.
        """
        ic = rng.integers(0, 2, size=width, dtype=np.uint8)
        return self.evolve(ic, n_steps)
